version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - cloud-network

  backend:
    build: ./backend
    ports:
      - "8081:3000"
    environment:
      DB_HOST: db
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: "StrongPassword123!"
      DB_NAME: expense_tracker
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cloud-network

  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: cloud-db
    cap_add:
      - SYS_PTRACE
    environment:
      MSSQL_SA_PASSWORD: "StrongPassword123!"
      ACCEPT_EULA: "Y"
    volumes:
      - db-data:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'StrongPassword123!' -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s
    networks:
      - cloud-network

networks:
  cloud-network:
    driver: bridge

volumes:
  db-data:
